# Generated by Django 5.2.1 on 2025-05-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_usernames_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usernames',
        ),
    ]
