# Generated by Django 5.2.1 on 2025-06-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_member_unique_together_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturador',
            name='tiene_trampa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='casa_acogida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tiene_relevo',
            field=models.BooleanField(default=False),
        ),
    ]
