# Generated by Django 5.2.1 on 2025-06-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_usernames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_file',
            field=models.ImageField(upload_to='users/img/'),
        ),
    ]
