# Generated by Django 5.2.1 on 2025-06-04 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_association_email_association_location_and_more'),
        ('users', '0004_alter_user_avatar_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='association.association'),
        ),
    ]
