# Generated by Django 5.2.1 on 2025-06-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_capturador_tiene_trampa_user_casa_acogida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='volunteer_number',
            new_name='carnet_gatos',
        ),
    ]
