# Generated by Django 5.2.1 on 2025-06-05 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_alter_manager_association'),
        ('users', '0005_alter_member_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='association.association'),
        ),
    ]
