# Generated by Django 5.2.1 on 2025-06-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_volunteer_number_user_carnet_gatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
