# Generated by Django 5.2.1 on 2025-07-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_file',
        ),
    ]
