# Generated by Django 5.2.1 on 2025-07-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_capturador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='es_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tiene_trampa',
            field=models.BooleanField(default=False),
        ),
    ]
