# Generated by Django 5.2.1 on 2025-07-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_es_capturador_user_es_free_user_tiene_trampa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='free',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='free',
            name='user',
        ),
        migrations.DeleteModel(
            name='Capturador',
        ),
        migrations.DeleteModel(
            name='Free',
        ),
    ]
