# Generated by Django 5.2.1 on 2025-09-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_capturador_free_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='carnet_gatos',
            field=models.ImageField(blank=True, null=True, upload_to='users/img/'),
        ),
    ]
