# Generated by Django 5.2.1 on 2025-09-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_carnet_gatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrapType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trap_types',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='tiene_trampa',
        ),
        migrations.AddField(
            model_name='user',
            name='trap_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.traptype'),
        ),
    ]
