# Generated by Django 5.2.1 on 2025-06-17 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
        ('colonies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonies.location'),
        ),
        migrations.AddField(
            model_name='manager',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='association_managers', to='association.association'),
        ),
    ]
