# Generated by Django 5.2.1 on 2025-06-04 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_initial'),
        ('municipality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='email',
            field=models.EmailField(blank=True, max_length=242, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='association',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipality.location'),
        ),
        migrations.AddField(
            model_name='association',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='association/img/'),
        ),
        migrations.AddField(
            model_name='association',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_managers', to='association.association'),
        ),
    ]
