# Generated by Django 5.2.1 on 2025-06-04 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_association_email_association_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='association_managers', to='association.association'),
        ),
    ]
