# Generated by Django 5.2.1 on 2025-06-18 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colonies', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.manager'),
        ),
        migrations.AddField(
            model_name='colony',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='council',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonies.location'),
        ),
        migrations.AddField(
            model_name='colony',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonies.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonies.municipality'),
        ),
    ]
