# Generated by Django 5.2.1 on 2025-06-18 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='zone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colonies.zone'),
        ),
    ]
