# Generated by Django 5.2.1 on 2025-06-25 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0005_remove_colony_users_colony_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='colonies.colony')),
            ],
        ),
    ]
