# Generated by Django 5.2.1 on 2025-06-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0006_incident'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incident',
            table='incidents',
        ),
    ]
