# Generated by Django 5.2.1 on 2025-07-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0007_alter_incident_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
