# Generated by Django 5.2.1 on 2025-07-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0008_incident_end_date_incident_resolution_and_more'),
        ('veterinarian', '0012_delete_agreement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Council',
        ),
    ]
