# Generated by Django 5.2.1 on 2025-09-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0010_relief_incident_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='users_colony',
            field=models.TextField(blank=True, null=True),
        ),
    ]
