# Generated by Django 5.2.1 on 2025-09-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0011_colony_users_colony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colony',
            name='manager',
        ),
    ]
