# Generated by Django 5.2.1 on 2025-09-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0012_remove_colony_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='nombre',
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('URG', 'Urgencia'), ('VAN', 'Vandalismo'), ('CON', 'Conflicto vecinal'), ('ENF', 'Enfermedad'), ('ABD', 'Abandono'), ('PAR', 'Parto'), ('CER', 'CER')], default='URG', max_length=3),
        ),
    ]
