# Generated by Django 5.2.1 on 2025-09-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0013_remove_location_description_remove_location_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relief',
            name='alert_type',
            field=models.CharField(choices=[('REL', 'Necesidad de relevo'), ('LIM', 'Necesidad de limpieza'), ('REF', 'Necesidad de refugios'), ('SOL', 'Red Solidaria')], default='REL', max_length=3),
        ),
        migrations.AddField(
            model_name='relief',
            name='title',
            field=models.CharField(default='Relevo sin título', max_length=200),
        ),
    ]
