# Generated by Django 5.2.1 on 2025-09-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0014_relief_alert_type_relief_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relief',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
