# Generated by Django 5.2.1 on 2025-09-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0015_alter_relief_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relief',
            options={'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
    ]
