# Generated by Django 5.2.1 on 2025-06-09 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del lugar')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('general', 'General'), ('turismo', 'Turismo'), ('gastronomia', 'Gastronomía'), ('cultura', 'Cultura'), ('naturaleza', 'Naturaleza'), ('comercio', 'Comercio')], default='general', max_length=20, verbose_name='Categoría')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitud')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Popup de Ubicación',
                'verbose_name_plural': 'Popups de Ubicación',
                'db_table': 'municipality_locationpopup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('popup_html', models.TextField(blank=True, help_text='HTML personalizado para el popup (opcional)', null=True, verbose_name='HTML Personalizado')),
                ('icon_color', models.CharField(choices=[('blue', 'Azul'), ('red', 'Rojo'), ('green', 'Verde'), ('purple', 'Morado'), ('orange', 'Naranja'), ('darkblue', 'Azul Oscuro'), ('lightred', 'Rojo Claro'), ('beige', 'Beige'), ('darkgreen', 'Verde Oscuro'), ('cadetblue', 'Azul Cadete'), ('darkpurple', 'Morado Oscuro'), ('white', 'Blanco'), ('pink', 'Rosa'), ('lightblue', 'Azul Claro'), ('lightgreen', 'Verde Claro'), ('gray', 'Gris'), ('black', 'Negro'), ('lightgray', 'Gris Claro')], default='blue', max_length=20, verbose_name='Color del Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipality.location', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Popup de Mapa',
                'verbose_name_plural': 'Popups de Mapa',
                'db_table': 'map_popups',
            },
        ),
    ]
