# Generated by Django 5.2.1 on 2025-06-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipality', '0002_locationpopup_mappopup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappopup',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='LocationPopup',
        ),
        migrations.DeleteModel(
            name='MapPopup',
        ),
    ]
