# Generated by Django 5.2.1 on 2025-06-23 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agreementService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinarian.agreement')),
                ('vet_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinarian.vetservice')),
            ],
            options={
                'db_table': 'agreement_services',
                'unique_together': {('agreement', 'vet_service')},
            },
        ),
    ]
