# Generated by Django 5.2.1 on 2025-06-25 07:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0002_agreementservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='agreementservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
