# Generated by Django 5.2.1 on 2025-06-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0003_agreementservice_price_agreementservice_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetcenter',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='veterinarian/img/'),
        ),
    ]
