# Generated by Django 5.2.1 on 2025-07-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0004_alter_vetcenter_logo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='agreement',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, upload_to='veterinarian/field/agreements'),
        ),
        migrations.AddField(
            model_name='visit',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='follow_up',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='bill_file',
            field=models.FileField(upload_to='veterinarian/field/visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='report_file',
            field=models.FileField(upload_to='veterinarian/field/visit'),
        ),
    ]
