# Generated by Django 5.2.1 on 2025-07-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0005_remove_visit_visit_date_agreement_agreement_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to='veterinarian/field/visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='veterinarian/field/visit'),
        ),
    ]
