# Generated by Django 5.2.1 on 2025-07-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0006_alter_visit_bill_file_alter_visit_report_file'),
    ]

    operations = [
    ]
