# Generated by Django 5.2.1 on 2025-07-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0007_remove_visitservice_vet_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitservice',
            name='vet_service',
        ),
        migrations.AlterUniqueTogether(
            name='visitservice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='visitservice',
            name='visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='cat_survived',
            field=models.BooleanField(default=True, verbose_name='¿El gato sobrevivió?'),
        ),
        migrations.DeleteModel(
            name='agreementService',
        ),
        migrations.DeleteModel(
            name='VetService',
        ),
        migrations.DeleteModel(
            name='VisitService',
        ),
    ]
