# Generated by Django 5.2.1 on 2025-07-08 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_avatar_file'),
        ('veterinarian', '0008_remove_visitservice_vet_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.association'),
        ),
    ]
