# Generated by Django 5.2.1 on 2025-07-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_avatar_file'),
        ('veterinarian', '0009_agreement_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetcenter',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.association'),
        ),
        migrations.AddField(
            model_name='visit',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.association'),
        ),
    ]
