# Generated by Django 5.2.1 on 2025-07-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0010_vetcenter_association_visit_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetcenter',
            name='association',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='association',
        ),
    ]
