# Generated by Django 5.2.1 on 2025-07-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0011_remove_vetcenter_association_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agreement',
        ),
    ]
