# Generated by Django 5.2.1 on 2025-09-12 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_remove_cat_dead_cat_status'),
        ('colonies', '0016_alter_relief_options'),
        ('veterinarian', '0012_delete_agreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='colony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colonies.colony'),
        ),
        migrations.AddField(
            model_name='visit',
            name='colony_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colony_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='housing_address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de acogida/adopción'),
        ),
        migrations.AddField(
            model_name='visit',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('none', 'Ninguno'), ('foster', 'Casa de acogida'), ('adoption', 'Adopción')], default='none', max_length=10, null=True, verbose_name='Tipo de alojamiento'),
        ),
        migrations.AddField(
            model_name='visit',
            name='returned_to_colony',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Ha vuelto a la colonia?'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cats.cat'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='vet_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veterinarian.vetcenter'),
        ),
    ]
