# Generated by Django 5.2.1 on 2025-06-12 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
        ('colonies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='colony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colonies.colony'),
        ),
    ]
