# Generated by Django 5.2.1 on 2025-07-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='dead',
            field=models.BooleanField(choices=[(False, 'Vivo'), (True, 'Muerto')], default=False, verbose_name='Estado del gato'),
        ),
    ]
