# Generated by Django 5.2.1 on 2025-05-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cat',
            name='chip',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='photo_file',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
