# Generated by Django 5.2.1 on 2025-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_alter_cat_dead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='dead',
        ),
        migrations.AddField(
            model_name='cat',
            name='status',
            field=models.CharField(choices=[('V', 'Vivo'), ('E', 'Enfermo'), ('M', 'Muerto')], default='V', max_length=1, verbose_name='Estado del gato'),
        ),
    ]
