# Generated by Django 5.2.1 on 2025-05-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_alter_cat_birthday_alter_cat_chip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='photo_file',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
