# Generated by Django 5.2.1 on 2025-09-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_remove_cat_dead_cat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='illness_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la enfermedad'),
        ),
    ]
