# Generated by Django 5.2.1 on 2025-05-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_alter_cat_photo_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='name',
            new_name='catname',
        ),
        migrations.AlterField(
            model_name='cat',
            name='photo_file',
            field=models.ImageField(upload_to='cats/img/'),
        ),
    ]
