# Generated by Django 5.2.1 on 2025-10-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_cat_illness_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='sex',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra'), ('U', 'Indefinido')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='cat',
            name='status',
            field=models.CharField(choices=[('V', 'Sano'), ('E', 'Enfermo'), ('M', 'Muerto')], default='V', max_length=1, verbose_name='Estado del gato'),
        ),
    ]
