# Generated by Django 5.2.1 on 2025-05-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_rename_name_cat_catname_alter_cat_photo_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='catname',
            new_name='name',
        ),
    ]
