# Generated by Django 5.2.1 on 2025-05-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_rename_catname_cat_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='name',
            new_name='catname',
        ),
    ]
